### ISSUE TITLE
Systems for entities that explicitly *don't* have a specific component

### ISSUE THREAD

**Issue by EriKWDev** [rlipsc/polymorph#12]
## The problem
Hi again! Is there a way to create a system for entities without a specific component?

I need to render Tiles differently from all other sprites in my game. One (dumb?) way of doing it would be to:
```nim
makeSystem "render", [ Transform, Sprite ]:
  fields:
    window: Window

  start:
    glClearColor(0.0, 0.0, 0.0, 0.0)
    glClear(GL_COLOR_BUFFER_BIT)

  all:
    # Check if there is a  Tile component:
    if entity.has(Tile):
      let tile = entity.fetch Tile
      discard # render tile...
    else:
      discard # render normal sprite...

  finish:
    sys.window.swapBuffers()
```

However, this seems very inefficient since I feel like that would break the ECS pattern a bit by getting a Component that the system "isn't meant to deal with". This would also not guarantee order of execution on the different entity groups. (I want to first render all Tiles, then all "normal" Sprites)

## Current Workaround
The solution I'm using currently is that I added a `sprite` field to the Tile component.
```nim
registerComponents, defaultComponentOptions:
    Sprite = object
      spriteId: int

    Tile = object
      spriteId: int
      tileMapX: int
      tileMapY: int


makeSystem "renderTiles", [ Transform, Tile ]:
  all:
    discard # Renders all tiles

makeSystem "renderSprites", [ Transform, Sprite ]:
  all:
    discard # Renders all sprites
```
But this is not so nice since now all other Systems that use `Sprite` will have to be "copied" (templated..) over to systems with a `Tile`.

## What would be nice
It would be nice if I could specify one system  for all entities *without* a specific component, and then one for all others. Is there a way to do this currently? I didn't find it in the docs.

I imagine a sort of `not`-wrapper like so:
```nim

makeSystem "renderTiles", [ Transform, Sprite, Tile]:
  all:
    discard # Render all Tile sprites

makeSystem "renderSprites", [ Transform, Sprite, not Tile ]:
  all:
    discard # Render Normal sprites
```

### This doesn't work, right?
I haven't tried inheritance of components yet. Might that work?
```nim
registerComponents, defaultComponentOptions:
    Sprite = object of RootObj
      spriteId: int

    NormalSprite = object of Sprite

    TileSprite = object of Sprite
      tileMapX: int
      tileMapY: int

makeSystem "render", [ Transform, TileSprite ]:
  all:
    discard # Renders all tiles

makeSystem "render", [ Transform, NormalSprite ]:
  all:
    discard # Renders all 'normal' sprites

# ...

makeSystem "otherSystem", [ Transform, Sprite ]:
  all:
    discard # Work on all entities with Sprite wether they are NormalSprite or TileSprite
```

I could ofc also add a `spriteType` enum to the tile and switch on that, but that wouldn't guarantee order of execution that  I need. I want tiles to be rendered first, then normal sprites after that.

**Comment by rlipsc** [comment]
Hi @EriKWDev.

## `not <component>`

>  Is there a way to create a system for entities without a specific component?

Systems are currently inclusive only.

The reason is mainly that, so far, I haven't needed it; every time I've been in that situation it's been easily/better solved by using components to split behaviour (see below).

Having said that, something like this will probably get implemented in a future version.

## Rendering tiles differently from all other sprites

### Using `has`

The first example with `has` isn't ideal for the reasons you mention. *Usually*, `has` is a 'code smell' when it's used in systems.

A possible exception that comes to mind is systems that `construct` entities and do something conditional for particular components. Usually it's better to use `fetch` and check the result is `valid` instead, as this only needs one lookup and can then use the component directly (compared to a lookup for `has` plus one for `fetch`).

Even then, it's probably easier/better/faster to use [events](https://github.com/rlipsc/polymorph#events).

For the rendering example, this seems like a waste as systems are there to segregate the work for you.

### Inheritance

This works in the sense that you can carry over the `spriteId` to the other component types, so you could have a `render` `proc` or `template` that takes these component types generically.

It doesn't work in the sense that "otherSystem" won't run for all types descending from `Sprite`, so "otherSystem" would only run for entities that explicitly have the `Sprite` component.

### Splitting behaviours and isolating responsibilities

> But this is not so nice since now all other Systems that use Sprite will have to be "copied" (templated..) over to systems with a Tile.

Your current approach of storing `spriteId` in `Tile` and `Sprite` is okay for your simple example of ordering sprite renders, but your inheritance example explains a bit more about what you need.

Namely, `Sprite` should be the only place that sprite data is stored, and how that data is processed might differ. Isolating component responsibility like this is where ECS comes into its own.

Here's how I would approach this:

```nim
registerComponents defaultComponentOptions:
  type
    Sprite = object
      spriteId: int

    Dynamic = object  # or 'NormalSprite'.

    Tile = object
      tileMapX: int
      tileMapY: int
    
makeSystem "renderTiles", [ Transform, Tile, Sprite ]:
  all: discard

makeSystem "renderDynamic", [ Transform, Dynamic, Sprite ]:
  all: discard

makeSystem "otherSystem", [ Transform, Sprite ]:
  # Run for entities regardless of 'Tile' or 'Dynamic'.
  all: discard
```

`Sprite` is now decoupled from other behaviours and is a simple store of data.

This lets you define `Dynamic`/`Tile`/`Sprite` specific systems, for example:

```nim
makeSystem "calcDamage", [ Health, Damage ]:
  # 'Damage' can only affect entities with 'Health'.
  all:
    item.health.amount -= item.damage.amount
    if item.health.amount <= 0.0:
      entity.addIfMissing Killed()

makeSystem "explodeFx", [ Killed, Transform, Dynamic, Sprite ]:
  # You could also constrain this system with an 'Explodes' component
  # containing data about the number of particles and colours.
  all: createParticleSprites(item.transform, item.sprite)

makeSystem "updateScore", [ Killed, Dynamic, Score ]:
  # 'Killed' could contain the killer entity if you want any entity to
  # accrue a score.
  # If you want destroying anything to affect score, simply remove the
  # 'Dynamic' requirement.
  all: updatePlayerScore(item.score.value)

makeSystem "crumbleTile", [ Killed, Tile, Sprite ]:
  all: crumbleFx(item.tile, item.sprite)

makeSystem "updateMap", [ Killed, Tile ]:
  # Regardless of whether the 'Tile' is rendered, pathfinding will be updated.
  all: updatePathfinding(item.tile)
```

This also means you can store sprite data on entities without rendering them, and add/remove `Dynamic`/`Tile` when you want them to be shown/hidden. This can give you some flexibility in how entities are managed whilst ensuring that entities are processed correctly according to their existing components.

You could even change entities from tiles into dynamic items or visa versa - perhaps a tree creature starts moving, or plants roots to become part of the map. Having `Sprite` as a simple data storage component also makes it easy to copy to/from other entities without worrying about separate or duplicated handling.

Taking this further, you can introduce a `Render` tag component and/or `Onscreen`/`Offscreen` so you can show or hide entities whilst maintaining other components. This can be useful for screen culling and/or performing different AI for entities far from the player, or for making entities temporarily invisible but retaining their full functionality.

As an aside, Polymorph makes it quite easy to [create entities](https://github.com/rlipsc/polymorph#constructing-entities-at-run-time) (or [update them](https://github.com/rlipsc/polymorph#updating-entities-with-component-lists)) using component lists if you want to handle spawning dynamically:

```nim
makeSystem "spawn", [ Transform, SpawnDynamic ]:
  all:
    # This could be a tile, other sprite, or a hidden spawning node.
    if item.spawnDynamic.conditions.doSpawn:
      let
        dynEntity = item.spawnDynamic.blueprint.construct
        transform = dynEntity.fetch Transform

      assert transform.valid
      # Move construction to current location/orientation.
      transform.update item.transform
```

Hopefully this has given you some ideas! For a working game example, you can also check out the [spaceshooter](https://github.com/rlipsc/polymers/blob/master/polymers/demos/spaceshooter.nim) demo that uses some of these principles.

**Comment by EriKWDev** [comment]
Fantastic and detailed response! Your suggestion of adding another `Dynamic` component now seems like the obvious solution. Thanks for pointing it out! This solves my simple problem and gives me the kind of flexibility I wanted with my inheritance example.

I have indeed checked the spaceshooter game demo and will be taking a closer look into the code tomorrow :) I notice that components were added and removed a lot which is a way of doing things that I'm not used to. I'm used to a more traditional approach like in Unity where data and behaviour is tightly coupled, but ever since I got to know ECS the benefits in performance and separation of concerns keep on amazing me.


This solved my problem, but should I leave the issue up for the potential of a semantic `not` for Component filtering for systems in the future?

**Comment by rlipsc** [comment]
Hi @EriKWDev,

>  adding another Dynamic component now seems like the obvious solution

I was originally going to reply to your above comment to talk about how ECS can be thought of as set operations vs inheritance using trees, but it got me thinking about what would be involved to implement `not` for systems. It has always been something on the `TODO` list, but as I mentioned above, it wasn't "necessary" as you can technically work around it by adding new components. The more I thought about it, the more I realised this was just a work around and negation makes for better designs.

Well, once I got into trying to implement `not`, it turns out it wasn't straightforward to implement at all and I had to completely rework the internals! I want to thank you for nudging me to do this though, because now I've done it, I think it hugely improves the ECS.

Component negation is now implemented in the 0.3.0 release here: https://github.com/rlipsc/polymorph/releases/tag/v0.3.0

> I have indeed checked the spaceshooter game demo

This demo has been massively improved! It now features font rendering, special weapons and all sorts.

> I notice that components were added and removed a lot which is a way of doing things that I'm not used to. I'm used to a more traditional approach like in Unity where data and behaviour is tightly coupled

Yeah adding/removing components can be very powerful and probably takes some getting used to compared to traditional object oriented approaches. For instance, removing `Velocity` temporarily can be useful for freezing something in an ECS, where in more object oriented styles this might be done with a switch that has to be integrated into the movement code. There's lots of approaches to doing things in ECS that require 'zero' code to implement just by virtue of how components and systems interact! For things like games in particular, I would argue that ECS is inherently (heh) superior to inheritance approaches.

**Comment by EriKWDev** [comment]
I saw your talk at Fosdem and heard you mentioned that systems could now specify not and I got really excited and thought of this discussion immediately xD

I've had a lot of great use of polymorph in my hobby projects and it inspired me to learn more about ECS in general. I actually implemented my own simpler query-based ECS "easyess" https://github.com/ErikWDev/easyess

The experience of implementing it myself, as well as watching numerous talks on the subject, taught me a lot about the benefits of the pattern :)

In easyess, I generate enums for every component registered using my macro and each entity has a set of these enums to describe which components they have (and not have)

This allows for a lot of specific querying such as having a 'not' and other set intersections and goodies. 

Polymorph has much greater performance than easyess in my limited testing though and Polymorph is still what I use mostly for my projects :) Will see if I can update my tile renderer to use this feature now!

**Comment by EriKWDev** [comment]
I saw your talk at Fosdem and heard you mentioned that systems could now specify not and I got really excited and thought of this discussion immediately xD

I've had a lot of great use of polymorph in my hobby projects and it inspired me to learn more about ECS in general. I actually implemented my own simpler query-based ECS "easyess" https://github.com/ErikWDev/easyess
https://forum.nim-lang.org/t/8980

The experience of implementing it myself, as well as watching numerous talks on the subject, taught me a lot about the benefits of the pattern :)

In easyess, I generate enums for every component registered using my macro and each entity has a set of these enums to describe which components they have (and not have)

This allows for a lot of specific querying such as having a 'not' and other set intersections and goodies. 

Polymorph has much greater performance than easyess in my limited testing though and Polymorph is still what I use mostly for my projects :) Will see if I can update my tile renderer to use this feature now!

**Comment by EriKWDev** [comment]
I suppose we can close this issue now? @rlipsc

**Comment by rlipsc** [comment]
Oh cool, I'll take a look - it sounds like you've definitely caught the ECS bug! 😀 If you haven't read it already, you might also find [this article](https://www.sebaslab.com/the-quest-for-maintainable-code-and-the-path-to-ecs/) from the README interesting. It talks about how object oriented design's SOLID principles relate to designing with ECS, giving a nice bridge between the two paradigms.

And yes, this issue should be closed as the feature is implemented.
