### ISSUE TITLE
Ability to alias components (and/or disable `item.` in systems)

### ISSUE THREAD

**Issue by EriKWDev** [rlipsc/polymorph#18]
## The pattern and "problem"

A pattern I see when using polymorph is that I have some component, say a `Transform` with a position and `Physics` with a velocity, as well as a component with a long name:
```nim
register defaultCompOpts:
  type
    Transform = object
      position: Vector3

    Physics = object
      velocity: Vector3

    AVerySpecificComponentName = object
      val: int
```

This means that I in a system have to access them using `item.<componentName>.<param>`. For systems that accesses a lot of component parameters, it becomes a bit long and repetetive to call `item.<componentName>.<actuallyRelevantParam>` every time:

```nim
makeSystem "moveSystem", [Transform, Physics, AVerySpecificComponentName]:
  all:
    item.transform.position += item.physics.velocity
    if item.aVerySpecificComponentName.val > 0:
      echo item.aVerySpecificComponentName.val
```

I rarely have name conflicts within components used in the same system, so I often end up writing templates:

```nim
makeSystem "moveSystem", [Transform, Physics, AVerySpecificComponentName]:
  all:
    template position: Vector3 = item.transform.position
    template velocity: Vector3 = item.physics.velocity
    template value: int = item.aVerySpecificComponentName.val
   
    # much nicer:
    position += velocity 
    if value > 0:
      echo value
```

## Proposed syntax
A compromise perhaps would be something similair to what I do in `easyess` which uses syntax that mimics normal parameters in a proc and other parameter declarations in nim:

```nim
makeSystem "moveSystem", [trans: Transform, phys: Physics, theComp: AVerySpecificComponentName]:
  all:
    # Not as sugary as above, but better IMO:
    trans.position += phys.velocity 
    if theComp.val > 0:
      echo theComp.val
```
This removes the need to constantly type `item.` which helps a lot  IMO and it also allows for many of the benefits that naming parameters in a proc normally comes with. 

What could happen internally could perhaps be an injection of templates inside the system block being used similair to the ones I typed manually above^:
```nim
template phys: PhysicsInstance = item.physics
#        ^^^^-- The alias 
```

This would perhaps not interfere too much with the exclusive `not` syntax either since the item explicitly doesn't have not:ed component  so there would be no reason to alias a varaible to it.

While I could of course simply rename my types in the start to `Trans` and `Phys`, I personally do not like to have cryptic type names and instead prefer shortening variable names. This is ofc just a personal preference of mine but it makes sense to me.

---

## A related proposal: Option to disable the need to type `item.` within systems?
A related thing would perhaps oe to have an option within `ECSSysOptions` that would create a template for each component within a system eliminating the need to call `item.` at all. Something like:

```nim
const mySysOpts = ECSSysOptions(noItem: true, #[ ... ]#)

makeSystem "moveSystem", [Transform, Physics, theComp: AVerySpecificComponentName], mySysOpts:                                 
  all:
    transform.position += physics.velocity 
    if theComp.val > 0:
      echo theComp.val
``` 

This proposal is not exclusive to the alias syntax above as `theComp`^  could still be aliased/renamed here.
The options could be called `noItem`, `templateComponents` or anything else.

One could still call `item.add() #, fetch, has ...` and so on using `item.`, but I find myself accessing components much more often than adding/removing them so it doesn't bother me.

I feel like all I do is complain on polymorph without contributing xD
Nothing but love <3 Thanks for making this package.

**Comment by rlipsc** [comment]
Hi @EriKWDev!

> I feel like all I do is complain on polymorph without contributing xD
Nothing but love <3 Thanks for making this package.

First off, you are contributing! 1) by using the library and 2) by making these feedback issues so it can be improved.

So, thank you for your time on both points :) These kind of friction points only come up when the library is used 'in anger', and it's very useful to have other perspectives.

Sometimes it's enough to make me realise I've just got used to hacking around something that is actually a usability problem, as in this case. A similar thing happened with your component negation issue/question, which made me consider the wider scope of patterns that could be achieved with the library and provided the impetuous to make a fundamental change that might have otherwise been on the back burner for ages.

> it becomes a bit long and repetetive to call item.<componentName>.<actuallyRelevantParam> every time

I actually encounter this constantly and end up paradoxically writing boilerplate to make my code more concise. For systems with many components, I've seen this aliasing code take up more lines that the functional code!

Aside from templates, another thing you can do is copy instances from `item`:

```nim
makeSystem "moveSystem", [Transform, Physics, AVerySpecificComponentName]:
  all:
    let
      t = item.transform
      p = item.physics
      vsc = item.aVerySpecificComponentName

    t.position += p.velocity
    if vsc.val > 0:
      echo vsc.val
```

Copying instances like this shouldn't have any performance hit and will very likely be optimised away by the compiler. I can imagine others taking this shortcut too as it's a slightly shorter boilerplate than templates.

Only... there are two *major* issues with copying from `item` like this instead of templates:

1) Copying instances means you don't get the static checking of `item`:
    ```nim
    makeSystem "oops", [Comp]:
      all:
        let c = item.comp
        entity.remove Comp
        # Oh dear, the following line compiles even though the 'c' instance
        # is junk.
        echo c
        # If this is the only/last item in the system and boundary checks
        # are on this raises an index defect at run time.
        # If boundary checks aren't on... ¯\_(ツ)_/¯
        #
        # But... what if it isn't the last item? No worries, it'll just use
        # the next item's component data! Yeah this will be fun to debug...
      all:
        entity.remove Comp
        # Using 'item' directly catches this at compile time:
        # "Error: potentially unsafe access of 'item' due to a removal of component(s) that affect this system".
        echo item.comp
    ```
    
2) If you later make components inline (owned), the semantics of `let c = item.component` changes from referencing the original component to copying the component data. This would mean edits to `c` would raise an error from the compiler, but if the assignment used `var`, it could mean changes to `c` are silently editing a copy and effectively discarded. That might also be annoying to debug, especially as the user's system code hasn't actually changed so it might not be immediately obvious.

So, really, doing this with instances is kind of an anti-pattern. It's okay in the short term, but it can hide potential issues as the complexity increases. I'm guilty of doing this instance copying for the reasons you made this issue, and it's probably bitten me even if I haven't realised exactly where!

> what I do in easyess which uses syntax that mimics normal parameters in a proc and other parameter declarations in nim

I saw this in and thought it was really neat! It makes complete sense to add this to the component signature. As an aside, I plan on having an `{.ecsSystem.}` or similar pragma for translating `proc` definitions to systems some when. This aliasing feature makes that easier to implement.

> What could happen internally could perhaps be an injection of templates inside the system block

Good call. I went ahead an implemented this in my local branch.

> I rarely have name conflicts within components used in the same system

> Option to disable the need to type item. within systems?

I actually made this the default and you can turn this off using `EcsSysOptions(itemTemplates: sitNone)` if these clash with existing variables, or if you're simply not using it or feel the extra templates are slowing down compilation.

What I did was when `item` is output, `template componentName: untyped = item.componentName` is output for each of the system's requirements. This means you don't have to use `item`, but the static checking is still enforced.

The aliases, if defined, are always output as `template alias: untyped = item.component`. I didn't provide an option to turn off aliasing templates because they're part of the system signature so I feel they should be guaranteed. When an alias is provided it's checked to make sure it matches aliases for the same component in `defineSystem`, if present.

Example of how that looks:

```nim
makeSystem "moveSystem", [t: Transform, Physics, vsc: AVerySpecificComponentName]:
  all:
    t.position += physics.velocity
    if vsc.val > 0:
      echo vsc.val
```

All in all, I think this is quite a big usability improvement as well as potentially reducing extremely un-fun bugs, so thank you for suggesting it!

What I would say though, is it will break a lot of (my) code that does this instance copying with redefinition errors. This is probably a good thing to be honest. It won't break your code that uses templates though, as templates can shadow each other without issue.

I'm a bit behind with pushing commits at the moment, so I'll update this issue when the feature is available. You might be interested to know that the pending commits include lots of stuff to make things easier when working with larger projects, such as committing across module boundaries and relative imports :)

**Comment by EriKWDev** [comment]
Sorry for a late written reply. 

> First off, you are contributing! 1) by using the library and 2) by making these feedback issues so it can be improved.

Glad to hear that you see it that way :)

> I went ahead an implemented this in my local branch.

Great to hear! Looking forward to testing it! Maybe push it to a devel/testing branch and I could give feedback!

> As an aside, I plan on having an {.ecsSystem.} or similar pragma for translating proc definitions to systems somewhen.

I recently implemented this in my local branch of `easyess`. I felt that the macro syntax started to feel  a bit foreign to Nim's default syntax so I backed down a bit and made more use of pragmas. The syntax is a bit different and looks like this now:

```nim
import easyess

type
  Position {.comp.} = Vector2

  Velocity {.comp.} = Vector2

  MovementState {.comp.} = enum
    msMoving, msStill

proc positionSystem(ecs: ECS) {.sys: (pos: Position, Velocity, state: MovementState), group: "logicSystems".} =
  for item in ecs.queryAllItems(signature):
    item.pos += item.velocity
    item.velocity *= 0.97

    if length(item.velocity) < 0.2:
      item.state = msStill
    else: 
      item.state = msMoving

# or {.allSys.} would inject the query iterator automatically and remove the need for `item.`:
when false:
  proc positionSystem(ecs: ECS) {.allSys: (pos: Position, Velocity), group: "logicSystems".} =
    pos += velocity
    velocity *= 0.97

    if length(velocity) < 0.2: state = msStill
    else: state = msMoving

makeECS()
```

It all expands to something like the following:
```nim
# ... component definitions here ...

type
  ComponentKind* = enum
    ckPosition, ckVelocity, ckMovementState

  Signature* = set[ComponentKind]

  ECS* = ref object
    signatures*: Slottable[Signature]
    positionContainer*: HeapArray[Position]
    velocityContainer*: HeapArray[Velocity]
    # ... for all components

# ...  newEntity, queryAlldraw and more...

template position*(item: Item): Position =
  assert ckPosition in item[0].signatures[item[1]]
  item[0].positionContainer[item[1].idx]

template `position=`*(item: Item; position: Position) =
  if ckPosition notin item[0].signatures[item[1]]:
    item.addPosition(position)
  else:
    item[0].positionContainer[item[1].idx] = position

# ... for all components and more

proc positionSystem*(ecs: ECS) =
  template signature(): Signature {.used.} =
    {ckPosition, ckVelocity, ckMovementState}

  template pos(item: Item): Position {.used.} =
    item.position

  template `pos=`(item: Item; pos: Position) {.used.} =
    item.position=(pos)

  template pos(entity: Entity): Position {.used.} =
    (ecs, entity).position

  template `pos=`(entity: Entity; pos: Position) {.used.} =
    (ecs, entity).position=(pos)

  # ... for all components

  when true:
    for item in ecs.queryAllItems(signature):
      item.pos += item.velocity
      item.velocity *= 0.97

    if length(item.velocity) < 0.2:
      item.state = msStill
    else: 
      item.state = msMoving

## === System Groups ===
template runLogicSystems*(ecs: ECS) =
  ## Runs every system in the group 'logicSystems' (1 systems)
  ecs.positionSystem()
```

Regarding the templates as you see, I had to also implement `<componentName>=` to be able to reassign all the components. Furthermore, I have the `{.used.}` pragma as well because I don't want to nag the user for not using all permutations of supported syntax in there xP

The reason that I put components inside the pragma and not simply inside of the formalParams of the proc is that easyess supports passing extra parameters to systems such as a `context: Context` or `game: Game` with some state of your game/application or perhaps other things like input, deltatime....

I could loop over all parameters and determine what is a Component and what isn't, but It could get messy so I chose to not go down that route.

Polymorph could probably just parse the normal formalParams in its `{.ecsSystem.}`.

> The aliases, if defined, are always output as template alias: untyped = item.component

I have found that when using `untyped` as the template's return type, VSCode won't show the actual component type in the inspector while highlighting which at times can become confusing. 

![image](https://user-images.githubusercontent.com/19771356/161703562-9c742cba-8069-41aa-ad68-7eea8e01a176.png)
vs.
![image](https://user-images.githubusercontent.com/19771356/161703325-31c82249-db22-4656-b5ab-de19db19b688.png)



So I chose to explicitly type all the templates with the corresponding component's type:

![image](https://user-images.githubusercontent.com/19771356/161699495-80086256-f398-44ee-aea0-9491cc2dddc9.png)

If I've understood Polymorph correclty you implement the dotoperator `.` for a component instance's fields..? This might be what causes VSCode to not show any inspector info in polymorph which Is something I've also thought about (pointer got hidden from screenshot but it is hovering over `velocity`):

![image](https://user-images.githubusercontent.com/19771356/161702232-8fa3324e-f68b-4ceb-ab81-5324fbe7561d.png)

This is a completely different topic though xD But is relevant for the templates at least :)

**Comment by rlipsc** [comment]
Hi @EriKWDev!

This ended up taking a lot longer than I expected due to some edge cases that popped up in more complex code and prompted a lot of reworking, but the feature is finally live!

Here's an example of how it looks:

```nim
import polymorph

register defaultCompOpts: 
  type
    CompA = object
      val: int
    CompB = object

CompA.onInit:
  # Templates enabled/disabled with EcsCompOptions.eventTemplates.
  assert compA() == curComponent()
  compA.val = 1

makeSystem "example", [CompA, aliased: CompB]:
  # Templates enabled/disabled with EcsSysOptions.itemTemplates.
  all:
    # Access templates do the same static checks as item.
    assert compA() == item.compA
    # Aliasing doesn't change the name of the system's item field:
    assert aliased() == item.compB
    # Aliasing CompB elides the compB() template:
    assert not compiles(compB())
  added:
    echo "Adding ", compA(), " ", aliased()

# Aliasing with ownership:
makeSystem "owned", [ownedAlias: own CompA]:
  all:
    assert ownedAlias().type is CompA
```

It makes system code a lot less noisy, and I find myself using it all the time now (it's enabled by default).

> Maybe push it to a devel/testing branch and I could give feedback!

I'm changing my commit approach to do version branches soon, so it'll be easier to try partial features and changes.

> I have found that when using untyped as the template's return type, VSCode won't show the actual component type in the inspector while highlighting which at times can become confusing.

The new templates for accessing components are typed, so this is implemented! Whether it will make any difference to VSCode probably depends on how long nimsuggest takes to run the macros to get the return types though :) Hopefully you'll see some improvements!

> If I've understood Polymorph correclty you implement the dotoperator . and .= for a component instance's fields..? That is a more flexible system perhepas but it seems to make VSCode not give any info :/

That's correct. I used to have a code gen option for producing templates for each individual field, e.g., `template x(pos: PosInstance): float`, but found that too many templates can mess with overloading rules in a confusing way. I also tried a `proc` per field, but that has difference semantics since the proc will return a copy of the field, so I dropped that because it could be confusing, was extra work to maintain, and the `.`/`.=` overloads seemed to work better. Hopefully the return types for the new access templates make this easier for VSCode to deduce. It's a tricky one, perhaps there's a better way?

> I beleive polymorph already adds {.used.} on the item so just thought to remind to do it on aliases as well!

Yep, all the templates are tagged with `{.used.}`! I try to make sure there's no warnings from the library as it 'dilutes' warnings from user code. As a consumer of the library myself, I want the compile output to be as 'clean' as possible.

> easyess supports passing extra parameters to systems such as a context: Context or game: Game with some state of your game/application or perhaps other things like input, deltatime....

I handle this by allowing custom fields for systems, or just using globals for `dt`. I do want to implement an ECS context like this for a few reasons, but it's probably not going to surface for a while. It's likely the threading for #4 will get implemented before contexts, as I recently wrote (a prototype of) the code to plan isolated paths through system executions.

> Polymorph could probably just parse the normal formalParams in its {.ecsSystem.}.

Yeah, it'll probably just be a simple translation from `proc`, taking formalParams of `alias: ComponentType` over to `makeSystem`. Now that aliases are implemented, it makes this a lot easier!

By the way, easyecs looks like it's coming along well!
